//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gymme.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New workout.
        /// </summary>
        public static string AddEdit_NewWorkout {
            get {
                return ResourceManager.GetString("AddEdit_NewWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string AEWorkout_DetailLabel {
            get {
                return ResourceManager.GetString("AEWorkout_DetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AEWorkout_NameLabel {
            get {
                return ResourceManager.GetString("AEWorkout_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string AEWorkout_NoteLabel {
            get {
                return ResourceManager.GetString("AEWorkout_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymme.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exs.
        /// </summary>
        public static string Common_Exercises {
            get {
                return ResourceManager.GetString("Common_Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift.
        /// </summary>
        public static string Common_Lift {
            get {
                return ResourceManager.GetString("Common_Lift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        public static string Common_Reps {
            get {
                return ResourceManager.GetString("Common_Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string Common_Sets {
            get {
                return ResourceManager.GetString("Common_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Common_Statistics {
            get {
                return ResourceManager.GetString("Common_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string Common_Workouts {
            get {
                return ResourceManager.GetString("Common_Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap &quot;+&quot; to add an excercise.
        /// </summary>
        public static string Dummy_Exercises {
            get {
                return ResourceManager.GetString("Dummy_Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics is comming soon.
        /// </summary>
        public static string Dummy_Statistics {
            get {
                return ResourceManager.GetString("Dummy_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routines for today.
        /// </summary>
        public static string Main_UpcomingDummyText {
            get {
                return ResourceManager.GetString("Main_UpcomingDummyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Main_UpcomingWorkout {
            get {
                return ResourceManager.GetString("Main_UpcomingWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout in the menu →.
        /// </summary>
        public static string Main_WorkoutsDummyText {
            get {
                return ResourceManager.GetString("Main_WorkoutsDummyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout.
        /// </summary>
        public static string MainMenu_AddWorkout {
            get {
                return ResourceManager.GetString("MainMenu_AddWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will delete all information about this workout. Do you realy want to delete it?.
        /// </summary>
        public static string Workout_DeleteWarning {
            get {
                return ResourceManager.GetString("Workout_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete workout.
        /// </summary>
        public static string Workout_DeleteWarningTitle {
            get {
                return ResourceManager.GetString("Workout_DeleteWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete workout.
        /// </summary>
        public static string WorkoutPage_DeleteWorkout {
            get {
                return ResourceManager.GetString("WorkoutPage_DeleteWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit workout.
        /// </summary>
        public static string WorkoutPage_EditWorkout {
            get {
                return ResourceManager.GetString("WorkoutPage_EditWorkout", resourceCulture);
            }
        }
    }
}
