//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gymme.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymme app by D93 (2013-2014).
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.gymme@i.ua.
        /// </summary>
        public static string About_Email {
            get {
                return ResourceManager.GetString("About_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb.com/app.gymme.
        /// </summary>
        public static string About_Facebook {
            get {
                return ResourceManager.GetString("About_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Gymme&apos;s developer.
        /// </summary>
        public static string About_ReportSubject {
            get {
                return ResourceManager.GetString("About_ReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vk.com/app.gymme.
        /// </summary>
        public static string About_Vk {
            get {
                return ResourceManager.GetString("About_Vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string AddEdit_Exercise {
            get {
                return ResourceManager.GetString("AddEdit_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New workout.
        /// </summary>
        public static string AddEdit_NewWorkout {
            get {
                return ResourceManager.GetString("AddEdit_NewWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AEExercise_CategoryLabel {
            get {
                return ResourceManager.GetString("AEExercise_CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight mode.
        /// </summary>
        public static string AEExercise_WeightModeLabel {
            get {
                return ResourceManager.GetString("AEExercise_WeightModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without weight.
        /// </summary>
        public static string AEExercise_WithoutWeight {
            get {
                return ResourceManager.GetString("AEExercise_WithoutWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With weight.
        /// </summary>
        public static string AEExercise_WithWeight {
            get {
                return ResourceManager.GetString("AEExercise_WithWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string AEWorkout_DetailLabel {
            get {
                return ResourceManager.GetString("AEWorkout_DetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AEWorkout_NameLabel {
            get {
                return ResourceManager.GetString("AEWorkout_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string AEWorkout_NoteLabel {
            get {
                return ResourceManager.GetString("AEWorkout_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymme.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Command_Add {
            get {
                return ResourceManager.GetString("Command_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string Command_Continue {
            get {
                return ResourceManager.GetString("Command_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string Command_Finish {
            get {
                return ResourceManager.GetString("Command_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reorder.
        /// </summary>
        public static string Command_Reorder {
            get {
                return ResourceManager.GetString("Command_Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string Command_Start {
            get {
                return ResourceManager.GetString("Command_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exs.
        /// </summary>
        public static string Common_Exercises {
            get {
                return ResourceManager.GetString("Common_Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift.
        /// </summary>
        public static string Common_Lift {
            get {
                return ResourceManager.GetString("Common_Lift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        public static string Common_Reps {
            get {
                return ResourceManager.GetString("Common_Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Common_Result {
            get {
                return ResourceManager.GetString("Common_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string Common_Sets {
            get {
                return ResourceManager.GetString("Common_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string Common_Workouts {
            get {
                return ResourceManager.GetString("Common_Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap &quot;+&quot; to add an excercise.
        /// </summary>
        public static string Dummy_Exercises {
            get {
                return ResourceManager.GetString("Dummy_Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics is comming soon.
        /// </summary>
        public static string Dummy_Statistics {
            get {
                return ResourceManager.GetString("Dummy_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current exercise progress will be lost. Continue?.
        /// </summary>
        public static string Execute_SkipWarning {
            get {
                return ResourceManager.GetString("Execute_SkipWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip exercise.
        /// </summary>
        public static string Execute_SkipWarningTitle {
            get {
                return ResourceManager.GetString("Execute_SkipWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string ExecutePage_Done {
            get {
                return ResourceManager.GetString("ExecutePage_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string ExecutePage_Finish {
            get {
                return ResourceManager.GetString("ExecutePage_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ExecutePage_History {
            get {
                return ResourceManager.GetString("ExecutePage_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ExecutePage_Next {
            get {
                return ResourceManager.GetString("ExecutePage_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ExecutePage_Previous {
            get {
                return ResourceManager.GetString("ExecutePage_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise skiped. Use application menu to start..
        /// </summary>
        public static string ExecutePage_SkipedHint {
            get {
                return ResourceManager.GetString("ExecutePage_SkipedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skiped.
        /// </summary>
        public static string ExecutePage_SkipedItem {
            get {
                return ResourceManager.GetString("ExecutePage_SkipedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will delete all information about this exercise in workout. Do you realy want to delete it?.
        /// </summary>
        public static string Exercise_DeleteWarning {
            get {
                return ResourceManager.GetString("Exercise_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete exercise.
        /// </summary>
        public static string Exercise_DeleteWarningTitle {
            get {
                return ResourceManager.GetString("Exercise_DeleteWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ExercisePage_Category {
            get {
                return ResourceManager.GetString("ExercisePage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avg. weight.
        /// </summary>
        public static string ExercisePage_Chart_AvarageWeight {
            get {
                return ResourceManager.GetString("ExercisePage_Chart_AvarageWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max weight.
        /// </summary>
        public static string ExercisePage_Chart_MaxWeight {
            get {
                return ResourceManager.GetString("ExercisePage_Chart_MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notes.
        /// </summary>
        public static string ExercisePage_EmptyNoteHint {
            get {
                return ResourceManager.GetString("ExercisePage_EmptyNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExercisePage_Name {
            get {
                return ResourceManager.GetString("ExercisePage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ExercisePage_Notes {
            get {
                return ResourceManager.GetString("ExercisePage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose exercise.
        /// </summary>
        public static string ExercisesSelectPage_Title {
            get {
                return ResourceManager.GetString("ExercisesSelectPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymme is the new way to manage you trainings. It&apos;s oriented to powerlifting and fitness workouts. Now you haven&apos;t to keep your results in mind. Just type in current progress - next time Gymme will show and repeat it for you..
        /// </summary>
        public static string Guide_Line1 {
            get {
                return ResourceManager.GetString("Guide_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymme also tracks your activity. After two trainings it will suggest the date of the next, keeping your pace..
        /// </summary>
        public static string Guide_Line2 {
            get {
                return ResourceManager.GetString("Guide_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you enjoy this app!.
        /// </summary>
        public static string Guide_Line3 {
            get {
                return ResourceManager.GetString("Guide_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Help_About {
            get {
                return ResourceManager.GetString("Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Help_Guide {
            get {
                return ResourceManager.GetString("Help_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routines for today.
        /// </summary>
        public static string Main_UpcomingDummyText {
            get {
                return ResourceManager.GetString("Main_UpcomingDummyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Main_UpcomingWorkout {
            get {
                return ResourceManager.GetString("Main_UpcomingWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout in the menu →.
        /// </summary>
        public static string Main_WorkoutsDummyText {
            get {
                return ResourceManager.GetString("Main_WorkoutsDummyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout.
        /// </summary>
        public static string MainMenu_AddWorkout {
            get {
                return ResourceManager.GetString("MainMenu_AddWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainMenu_HelpButton {
            get {
                return ResourceManager.GetString("MainMenu_HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates &amp; Reviews.
        /// </summary>
        public static string MainMenu_RatesButton {
            get {
                return ResourceManager.GetString("MainMenu_RatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Page_Overview {
            get {
                return ResourceManager.GetString("Page_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Page_Statistics {
            get {
                return ResourceManager.GetString("Page_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Page_Statistics_Loading {
            get {
                return ResourceManager.GetString("Page_Statistics_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data to plot.
        /// </summary>
        public static string Page_Statistics_NoData {
            get {
                return ResourceManager.GetString("Page_Statistics_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetControl_Set {
            get {
                return ResourceManager.GetString("SetControl_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will delete current training progress. Continue?.
        /// </summary>
        public static string Training_DeleteWarning {
            get {
                return ResourceManager.GetString("Training_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete training.
        /// </summary>
        public static string Training_DeleteWarningTitle {
            get {
                return ResourceManager.GetString("Training_DeleteWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish training.
        /// </summary>
        public static string Training_Finish {
            get {
                return ResourceManager.GetString("Training_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip.
        /// </summary>
        public static string Training_Skip {
            get {
                return ResourceManager.GetString("Training_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string Training_Started {
            get {
                return ResourceManager.GetString("Training_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string Training_Time {
            get {
                return ResourceManager.GetString("Training_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string Up_At {
            get {
                return ResourceManager.GetString("Up_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Up_Today {
            get {
                return ResourceManager.GetString("Up_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Up_Tomorrow {
            get {
                return ResourceManager.GetString("Up_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Up_Yday {
            get {
                return ResourceManager.GetString("Up_Yday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will delete all information about this workout. Do you realy want to delete it?.
        /// </summary>
        public static string Workout_DeleteWarning {
            get {
                return ResourceManager.GetString("Workout_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete workout.
        /// </summary>
        public static string Workout_DeleteWarningTitle {
            get {
                return ResourceManager.GetString("Workout_DeleteWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time spent.
        /// </summary>
        public static string WorkoutPage_Chart_TimeSpent {
            get {
                return ResourceManager.GetString("WorkoutPage_Chart_TimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete workout.
        /// </summary>
        public static string WorkoutPage_DeleteWorkout {
            get {
                return ResourceManager.GetString("WorkoutPage_DeleteWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit workout.
        /// </summary>
        public static string WorkoutPage_EditWorkout {
            get {
                return ResourceManager.GetString("WorkoutPage_EditWorkout", resourceCulture);
            }
        }
    }
}
